print ("hello i am chatbot plus")
input()
print ("what is your name")
name = input()
print (f"hello {name} nice to meet you")
print ("how are you feeling today")
feeling = input()
print (f"nice! im also feeling {feeling}")
input()
print ("we are connecting super well!")
print ("dont you think?")
input ()
print ("thank you for telling me")
input()
print("do you have anymore feedback for chatbot plus")
feedback = input ()
print (f"thank you for telling us {feedback} we aprrciate it")