print ("hello i am chatbot plus")
input()
print ("what is your name")
name = input()
print (f"hello {name} nice to meet you")
print ("how are you feeling today")
feeling = input()
input()
print (f"im also feeling {feeling}")
print ("we are connecting super well!")
print ("dont you think?")